version: 2

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters: ["errcheck", "staticcheck"]
    - path: "examples/"
      linters: ["errcheck"]
    - path: "internal/testing/"
      linters: ["errcheck", "staticcheck"]
  exclude:
    - "Error return value of .*(Close|Flush|Remove|Stop|Write|Start|Build). is not checked"
    - "Error return value of .*fmt\\..*print.* is not checked"
    - "Error return value of .*\\.ShouldFail. is not checked"
    - "Error return value of .*\\.NotifyError. is not checked"
    - "SA9003: empty branch"
    - "SA6002: argument should be pointer-like"
    - "SA4023: this comparison is never true"
    - "S1039: unnecessary use of fmt.Sprintf"
  max-issues-per-linter: 10