run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    check-shadowing: true

  revive:
    min-confidence: 0

  goimports:
    local-prefixes: github.com/conneroisu/templar

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 2

  depguard:
    list-type: blacklist
    packages:
      - github.com/sirupsen/logrus

  misspell:
    locale: US

  lll:
    line-length: 140

  unused:
    check-exported: false

  unparam:
    check-exported: false

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 20

  nestif:
    min-complexity: 4

  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,return

  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK

  dogsled:
    max-blank-identifiers: 2

  whitespace:
    multi-if: false
    multi-func: false

  errorlint:
    errorf: true

  exhaustive:
    default-signifies-exhaustive: false

  godot:
    scope: declarations
    capital: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - godox
    - godot
    - prealloc
    - nestif
    - gocognit
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - dupl
        - lll

    - path: cmd/
      linters:
        - lll

    - path: internal/
      text: "should not use dot imports"

    - linters:
        - staticcheck
      text: "SA9003:"

    - linters:
        - lll
      source: "^//go:generate "

    - path: _test\.go
      linters:
        - gosec

    - path: integration_tests/
      linters:
        - gosec
        - funlen
        - gocognit
        - gocyclo

  exclude-use-default: false
  exclude:
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print.*|os\\.(Un)?Setenv). is not checked"
    - "^(G104|G204|G304|G404):"
    - "unnecessaryDefer:"

  max-issues-per-linter: 0
  max-same-issues: 0