# Golangci-lint configuration for Templar
# Optimized for performance, accuracy, and maintainability
# Compatible with golangci-lint v2.1.6

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules
  skip-files:
    - ".*\\.pb\\.go$"

# Configure individual linters
linters:
  enable:
    - errcheck      # Check for unchecked errors
    - staticcheck   # Comprehensive static analysis
    - govet         # Official Go tool for static analysis  
    - ineffassign   # Detect ineffectual assignments
  disable:
    - gocognit      # Too noisy for this project
    - goconst       # Legitimate repeated strings in tests
    - gocyclo       # Covered by other complexity checks

# Linter-specific settings
linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  govet:
    check-shadowing: false

# Issue exclusion rules
issues:
  exclude-use-default: false
  
  # Path-based exclusions (most efficient)
  exclude-rules:
    # Test files - allow more flexible error handling
    - path: "_test\\.go$"
      linters: ["errcheck"]
      
    # Testing utilities - allow unchecked errors
    - path: "internal/testing/"
      linters: ["errcheck", "staticcheck"]
      
    # Example code - prioritize readability  
    - path: "examples/"
      linters: ["errcheck"]
      
    # Integration tests - test-specific patterns
    - path: "integration_tests/"
      linters: ["errcheck"]
      
    # Command packages - defer cleanup often acceptable
    - path: "cmd/"
      linters: ["errcheck"]

  # Text pattern exclusions
  exclude:
    # Defer cleanup functions - typically safe to ignore
    - "Error return value of .*(Close|Flush|Remove|Stop|Write|Start|Build|Shutdown) is not checked"
    
    # Print functions - output errors rarely actionable
    - "Error return value of .*fmt\\.(Fprint|Print|Sprint).* is not checked"
    
    # Environment setup in tests
    - "Error return value of .*(os\\.(Setenv|Unsetenv|Chdir)|viper\\.BindEnv|filepath\\.Walk) is not checked"
    
    # Test utility functions
    - "Error return value of .*\\.(ShouldFail|NotifyError|Reset) is not checked"
    
    # Staticcheck rules that are overly strict
    - "SA9003: empty branch"
    - "SA6002: argument should be pointer-like"
    - "SA4023: this comparison is never true" 
    - "S1040: type assertion to the same type"
    - "S1039: unnecessary use of fmt\\.Sprintf"
    - "S1008: should use 'return.*' instead"
    - "SA4010: this result of append is never used"
    - "SA4011: ineffective break statement"
    - "S1031: unnecessary nil check around range"
    - "QF1001: could apply De Morgan's law"

  # Performance settings
  max-issues-per-linter: 50
  max-same-issues: 5