run:
  timeout: 5m

linters-settings:
  lll:
    line-length: 120

linters:
  enable:
    - govet
    - ineffassign
    - typecheck
    - unused
    - gofmt

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10