version: 2

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign

issues:
  exclude:
    - "Error return value of .*(Close|Flush|Remove). is not checked"
    - "Error return value of .*fmt\\..*print.* is not checked"
  max-issues-per-linter: 50