name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '[BUG] '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I am using the latest version of Templar
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: input
    id: version
    attributes:
      label: Templar Version
      description: What version of Templar are you using?
      placeholder: v1.0.0 (run `templar version`)
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your operating system and Go version
      placeholder: macOS 13.0, Go 1.21.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide minimal steps to reproduce the issue
      placeholder: |
        1. Run `templar init`
        2. Execute `templar serve`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Output
      description: Include relevant error messages, stack traces, or command output
      render: text
      placeholder: Paste logs here...

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration files (please redact sensitive information)
      render: yaml
      placeholder: |
        # .templar.yml
        server:
          port: 8080
          ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, screenshots, or context
      placeholder: Add any other context about the problem here...