name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: '[FEATURE] '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide detailed information to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues and discussions for similar requests
          required: true
        - label: This is a feature request, not a bug report
          required: true
        - label: I have considered if this could be achieved with existing features
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - CLI Command Enhancement
        - Development Server Feature
        - Component Scaffolding
        - Build Pipeline Improvement
        - WebSocket/Live Reload Feature
        - Configuration Management
        - Performance Optimization
        - Security Enhancement
        - Documentation/Help
        - Integration/Plugin
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        I'm trying to accomplish... but currently I can't because...
        This would help developers who need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred solution in detail
      placeholder: |
        I would like to see...
        This could work by...
        Example usage: `templar command --flag value`
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds have you considered?
      placeholder: |
        I also considered...
        Current workaround is...
        But this doesn't work because...

  - type: textarea
    id: examples
    attributes:
      label: Examples and Use Cases
      description: Provide concrete examples of how this feature would be used
      placeholder: |
        Example 1: When developing components for...
        Example 2: For projects that have...
        Example 3: This would enable...

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How would you rate the importance of this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
        - Critical - Blocking my adoption of Templar
    validations:
      required: true

  - type: checkboxes
    id: complexity
    attributes:
      label: Implementation Considerations
      description: Check any that apply to help with planning
      options:
        - label: This might require breaking changes
        - label: This could affect performance
        - label: This involves security considerations
        - label: This requires new dependencies
        - label: This affects the CLI interface
        - label: This affects the web interface
        - label: This requires documentation updates

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information, mockups, or references
      placeholder: |
        Links to similar features in other tools...
        Screenshots or mockups...
        Related discussions or issues...